### PR TITLE
Modified load averages to be consistent with other exporter, ie use s…

### PR DESCRIPTION
**Pull request by vladvasiliu**
Fix for #19.

### CODE REVIEW

**Comment by pjhampton** [comment]
Thanks for your contribution @vladvasiliu!

**Comment by vkudrik** [comment]
And what about 6.4.0?

**Comment by pjhampton** [comment]
Hi @vkudrik 

Please subscribe to https://github.com/pjhampton/kibana-prometheus-exporter/issues/35 and I will get this done soon.

**Comment by pjhampton** [comment]
Hi @vkudrik 

I have re-released with this patch in 6.4.0. others to follow. https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/6.4.0

**Pull request merged**
