### PR TITLE
fixup metrics name for cpu load avgs, refs PR #20.  Results in the fo…

### PR DESCRIPTION
**Pull request by davsouza**
…llowing error when scrapped by prometheus err="invalid metric type \"interval=\\\"1m\\\"} gauge\""

### CODE REVIEW

**Comment by pjhampton** [comment]
Thanks for expediting this @davsouza. I will do a release now.

**Comment by pjhampton** [comment]
Thanks again @davsouza. ❤️ 💛 💙 

This has been uploaded to
https://github.com/pjhampton/kibana-prometheus-exporter/releases/tag/6.2.2

**Comment by davsouza** [comment]
thx for the quick release 👍

**Comment by davsouza** [comment]
Hi, can you also merge this change ahead to 6.2.3 there are no differences in this code other than the version.  We need to make the change on our end.

**Comment by pjhampton** [comment]
Done. @davsouza 

Please star this repo to show support and help promote it :)

**Pull request merged**
